apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trace-dlq
  namespace: trace
  labels:
    app: trace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
